# Downloading dependencies
- name: Postgres dependencies
  become: yes
  apt:
    pkg:
      - build-essential
      - libreadline-dev
      - zlib1g-dev
      - flex
      - bison
      - libxml2-dev
      - libxslt-dev
      - libssl-dev
      - libsystemd-dev
      - libxml2-utils
      - uuid-dev
      - xsltproc

- name: Download LLVM & Clang
  become: yes
  apt:
    pkg:
      - llvm-11-dev
      - clang-11

- name: Download GCC 10
  become: yes
  apt:
    pkg:
      - gcc-10
      - g++-10

- name: Switch to GCC 10
  shell:
    cmd: update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 --slave /usr/bin/g++ g++ /usr/bin/g++-10 --slave /usr/bin/gcov gcov /usr/bin/gcov-10
  become: yes

# Building Postgres from source
- name: Postgres - download latest release
  get_url:
    url: https://ftp.postgresql.org/pub/source/v{{ postgresql_release }}/postgresql-{{ postgresql_release }}.tar.gz
    dest: /tmp
    checksum: "{{ postgresql_release_checksum }}"
    timeout: 60

- name: Postgres - unpack archive
  unarchive:
    remote_src: yes
    src: /tmp/postgresql-{{ postgresql_release }}.tar.gz
    dest: /tmp
  become: yes

- name: Setting CFLAGS (arm)
  set_fact:
    cflags: "-moutline-atomics -mtune=neoverse-n1 -fsigned-char"
  when: platform == "arm64"

- name: Setting CFLAGS (x86)
  set_fact:
    cflags: "-fsigned-char"
  when: platform == "amd64"

- name: Postgres - configure
  shell:
    cmd: CFLAGS='{{ cflags }}' LLVM_CONFIG=/usr/bin/llvm-config-11 CLANG=/usr/bin/clang-11 ./configure --with-llvm --with-openssl --with-systemd --with-uuid=e2fs --exec-prefix=/usr/lib/postgresql --datarootdir=/var/lib/postgresql
    chdir: /tmp/postgresql-{{ postgresql_release }}
  become: yes

- name: Postgres - build
  make:
    target: world
    chdir: /tmp/postgresql-{{ postgresql_release }}
  become: yes

- name: Postgres - install
  make:
    target: install-world
    chdir: /tmp/postgresql-{{ postgresql_release }}
  become: yes

# Add systemd file for Postgres
- name: import postgresql.service
  template:
    src: files/postgresql.service.j2
    dest: /etc/systemd/system/postgresql.service
  become: yes

# Put PG binaries in a directory under $PATH
- name: Find all files in /usr/lib/postgresql/bin
  find:
    paths: /usr/lib/postgresql/bin
  register: postgresql_bin

- name: Create symbolic links for Postgres binaries to /usr/bin/
  become: yes
  file:
    src: "{{ item.path }}"
    path: "/usr/bin/{{ item.path | basename }}"
    state: link
    force: yes
  with_items: "{{ postgresql_bin.files }}"

- name: Install Postgres contrib
  become: yes
  apt:
    pkg:
      - postgresql-client-{{ postgresql_major }}
      - postgresql-contrib-{{ postgresql_major }}

